### ISSUE TITLE
error message is null!

### ISSUE THREAD

**Issue by jinking** [tunnckoCore/exec-cmd#7]
![ttt](https://user-images.githubusercontent.com/6762940/33644317-f5f67326-da7e-11e7-805f-ad77578f2bd8.png)

**Comment by tunnckoCore** [comment]
It's pretty old package and I don't thinking to update it soon. It had another grounds behind him and another target. Now we have [execa](https://ghub.now.sh/execa) and extension to it [execa-pro](https://ghub.now.sh/execa-pro) on which you might be interested because it has similar features and ideas like `exec-cmd`. Just runs commands in series and few more things - read the README and API.

Thanks!
